// Generated by scripts/phase2/governance.mjs. Fixed limits from the final plan; no policy approval.
export const PHASE2_LIMITS = {
  "version": 1,
  "maxBulkItems": 100,
  "maxTermLength": 100,
  "maxMeaningLength": 1000,
  "maxExampleLength": 2000,
  "photosPerImport": 1,
  "maxEncodedBytes": 10485760,
  "maxEncodedWidth": 8192,
  "maxEncodedHeight": 8192,
  "maxEncodedPixels": 20000000,
  "processingLongEdge": 2200,
  "acceptedTypes": [
    "image/jpeg",
    "image/png",
    "image/webp"
  ],
  "maxNormalizedUtf16Units": 2000,
  "maxNerInputIds": 512,
  "maxNerBatchLines": 100,
  "maxNerBatchCharacters": 50000,
  "personExpansionWordsPerSide": 4,
  "hourlyImports": 20,
  "lifetimeImports": 2000,
  "lifetimeSourceItems": 20000
} as const;
