// Generated by build-dictionary.mjs. Distribution approval remains pending.
export const DICTIONARY_ASSETS = [
  {
    "id": "dictionary-words.utf8",
    "kind": "ocr",
    "version": "1",
    "source": "hermitdave/FrequencyWords@525f9b560de45753a5ea01069454e72e9aa541c6",
    "bytes": 390710,
    "sha256": "e103fcb8a9de805d862806523703bf9298e6cb6fd5aeafb81abfb8a16a696e93",
    "license": "CC-BY-SA-4.0",
    "url": "/local-ai-assets/dictionary/frequencywords-v1/words.utf8",
    "cacheSchemaVersion": 1
  },
  {
    "id": "dictionary-offsets.u32le",
    "kind": "ocr",
    "version": "1",
    "source": "hermitdave/FrequencyWords@525f9b560de45753a5ea01069454e72e9aa541c6",
    "bytes": 193652,
    "sha256": "646906baf4077cce70e1388072394c9d1054b4cd99e8826845c1598d698b040f",
    "license": "CC-BY-SA-4.0",
    "url": "/local-ai-assets/dictionary/frequencywords-v1/offsets.u32le",
    "cacheSchemaVersion": 1
  }
] as const;
