// Generated by policy-governance.mjs; approval is separate.
export const PRIVACY_POLICY_VERSION = 1 as const;
export const POLICY_ARTIFACT_HASHES = [
  {
    "path": "docs/personalized-english/phase2/limits.v1.json",
    "sha256": "2b8bede6566a13d55813dde9725cb9b8f71f32825df6fc0f14ba0eb564ffbacb"
  },
  {
    "path": "docs/personalized-english/phase2/runtime-profile.v1.json",
    "sha256": "55ec772495675355f835020fb31e20bcbeef3b551583a7a3d9360d47fd585a91"
  },
  {
    "path": "docs/personalized-english/phase2/stage1-patterns.v1.json",
    "sha256": "a38a9fd78f1ef91a39ecdcc3ff3885e78b5c5fc5af3c4a8b2aa380bf2635c03a"
  },
  {
    "path": "docs/personalized-english/phase2/sensitive-labels.v1.json",
    "sha256": "591eec8285e3a83a7ca6df2bf3c8e8c8406f3668130536457d133b50f68e3a12"
  },
  {
    "path": "docs/personalized-english/phase2/gazetteer.v1.json",
    "sha256": "1761b6efada587353d866c27da1c743f3eccff9e59ccbd7f81df881caebf12bb"
  },
  {
    "path": "docs/personalized-english/phase2/institution-patterns.v1.json",
    "sha256": "39654d848fb13423f42a7527dc1cad9fd0cff1eebd45679ccd9e5169d6857e6a"
  },
  {
    "path": "docs/personalized-english/phase2/ner-correction-rules.v1.json",
    "sha256": "a9d2eb5d5752c2e837e87edcb0ddb9fc118fe8a416a2f6bfe2b3cf000d5ce14c"
  },
  {
    "path": "docs/personalized-english/phase2/correction-fixtures.v1.json",
    "sha256": "4c2c85412ecd7509248a576b6ad0ef332aefd9b70c9727848296b8bbeb7fe7d3"
  },
  {
    "path": "docs/personalized-english/phase2/morphology.v1.json",
    "sha256": "2f4b86be41b04311888b106b3fe666064f681219f939f05ba40ed761fcfe26e3"
  },
  {
    "path": "docs/personalized-english/phase2/dictionary.v1.json",
    "sha256": "72d74ed354e1614ff781cc0af652ff8d118dc6c0beb86db31baa403755214c61"
  }
] as const;
