import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { checkPlanHash, validatePreparation } from "./preparation.mjs";

checkPlanHash(); validatePreparation();
const root = new URL("../../", import.meta.url);
const directory = "docs/personalized-english/phase2/";
const artifacts = ["limits.v1.json", "runtime-profile.provisional.json", "calibration.draft.json",
  "correction-fixtures.draft.json", "institution-patterns.draft.json"];
const limits = JSON.parse(readFileSync(new URL(directory + artifacts[0], root), "utf8"));
const expectedLimits = {
  version: 1, maxBulkItems: 100, maxTermLength: 100, maxMeaningLength: 1000, maxExampleLength: 2000,
  photosPerImport: 1, maxEncodedBytes: 10485760, maxEncodedWidth: 8192, maxEncodedHeight: 8192,
  maxEncodedPixels: 20000000, processingLongEdge: 2200, acceptedTypes: ["image/jpeg", "image/png", "image/webp"],
  maxNormalizedUtf16Units: 2000, maxNerInputIds: 512, maxNerBatchLines: 100, maxNerBatchCharacters: 50000,
  personExpansionWordsPerSide: 4, hourlyImports: 20, lifetimeImports: 2000, lifetimeSourceItems: 20000,
};
if (JSON.stringify(limits) !== JSON.stringify(expectedLimits)) throw new Error("Immutable plan limits changed");
const manifest = { version: "preparation-1", status: "LOCAL_IMPLEMENTATION_COMPLETE_EXTERNAL_EVIDENCE_PENDING",
  policyFreeze: false, deployed: false, sqlGeneration: "IMPLEMENTED_LOCALLY_BY_EXPLICIT_OWNER_DIRECTION_REPLAY_PENDING",
  artifacts: artifacts.map(name => ({ path: directory + name,
    sha256: createHash("sha256").update(readFileSync(new URL(directory + name, root))).digest("hex") })) };
const outputs = [
  [directory + "preparation-manifest.json", JSON.stringify(manifest, null, 2) + "\n"],
  ["app/_lib/local-ai/phase2-limits.generated.ts", "// Generated by scripts/phase2/governance.mjs. Fixed limits from the final plan; no policy approval.\nexport const PHASE2_LIMITS = " + JSON.stringify(limits, null, 2) + " as const;\n"],
];
const write = process.argv.includes("--write");
for (const [path, content] of outputs) {
  const url = new URL(path, root);
  if (write) writeFileSync(url, content);
  else if (readFileSync(url, "utf8") !== content) throw new Error("Generated preparation artifact drift: " + path);
}
console.log(write ? "Generated preparation hashes and fixed limits; policy/runtime remain provisional." : "Preparation hashes and generated limits match; no policy freeze claimed.");
